spring:
  application:
    name: Produtos API

  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
    hikari:
      data-source-properties:
        ssl: true
        sslmode: require

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true